version: '3.4'

services:
  application:
    image: ${DOCKER_REGISTRY-}application
    container_name: hackathon.api
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
        - "5000:5000"
        - "5001:5001"

  techchallenge.database:
    image: postgres:latest
    container_name: hackathon.database
    environment: 
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    volumes:
        - ./.containers/hackathon-db:/var/lib/postegresql/data
    ports:
        - "5432:5432"